name: New Purchase Order
description: Use this form to submit a purchase order. NU Teams purchases are usually made with a university credit card. Each purchase on this card has to be reconciled. Please limit form submissions to a single credit card purchase - e.g. one item, or a cart of multiple items from the same store. If you need to purchase from multiple stores, submit multiple purchase orders.
title: "max 75 characters, e.g. Bolts for NU-24"
labels: []
body:
- type: dropdown
  attributes:
    label: Team
    description: What team does this purchase apply to?
    multiple: false
    options:
      - NU Teams Admin
      - NU Racing
      - NU Rocketry
      - NU Marine
      - NU Brewing
    default: 0
  validations:
    required: false
- type: textarea
  attributes:
    label: Description
    description: Be verbose: tell us what you want, the quantity, and shipping/pickup option(s). Include links/part numbers. For complicated orders, attach a cart screenshot in the field below. If we can't work out what to buy, your PO will be rejected and you'll have to resubmit.
  validations:
    required: false
- type: textarea
  attributes:
    label: Cart Screenshot(s)
    description: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
