name: New Purchase Order
description: Use this form to submit a purchase order.
NU Teams purchases are usually made with a university credit card. Each purchase on this card has to be reconciled.
Please limit form submissions to a single credit card purchase - e.g. one item, or a cart of multiple items from the same store. If you need to purchase from multiple stores, submit multiple purchase orders.
title: "max 75 characters, e.g. Bolts for NU-24"
labels: []
body:
- type: dropdown
  attributes:
    label: Team
    description: What team does this purchase apply to?
    multiple: false
    options:
      - NU Teams Admin
      - NU Racing
      - NU Rocketry
      - NU Marine
      - NU Brewing
    default: 0
  validations:
    required: false
- type: input
    id: totalOrderCost
    attributes:
      label: Total Order Cost
      description: Give your best estimate - this will be updated by your team leader when the purchase is actually made. This cost is in AUD. If your order is in another currency, google the current conversion rate. Include shipping and GST - you can usually get an estimate for this by 'checking out' your cart.
      placeholder: $99.99
    validations:
      required: false
- type: textarea
  attributes:
    label: Description
    description: Be verbose in this section. Clearly lay out What you want purchased, The quantity of these you want, and what shipping/pickup option(s). If you don't specify a specific option, we will default to the cheapest/slowest. For individual items, you can/should include links, as well as part numbers. For complicated orders, it also helps to attach a cart screenshot in the field below. The more specific you are, the better. If we can't work out what to buy, your PO will be rejected and you'll have to resubmit.
  validations:
    required: false
- type: textarea
  attributes:
    label: Cart Screenshot(s)
    description: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
