name: Label Issue

on:
  issues:
    types:
      - opened

jobs:
  label-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Issue Label
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueDescription = github.context.payload.issue.body;

            console.log('Issue Description:', issueDescription);

            // Apply the "hello" label
            const labels = ['hello'];
            github.issues.addLabels({
              issue_number: github.context.payload.issue.number,
              owner: github.context.repo.owner,
              repo: github.context.repo.repo,
              labels: labels,
            });

            console.log('Label "hello" added to the issue.');
