name: Label Issue

on:
  issues:
    types:
      - opened

jobs:
  label-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Issue Label
        env:
          GITHUB_EVENT_ISSUE_BODY: ${{ github.event.issue.body }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_EVENT_ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          python - <<EOF
import os
from github import Github

# Get the issue body
issue_body = os.getenv('GITHUB_EVENT_ISSUE_BODY')

# Extract team name from the issue body
team_name_index = issue_body.find('### Team')
if team_name_index != -1:
    team_name_start = team_name_index + len('### Team')
    team_name_end = issue_body.find('\n', team_name_start)
    team_name = issue_body[team_name_start:team_name_end].strip()

    # Add the team name as a label
    github_token = os.getenv('GITHUB_TOKEN')
    repository = os.getenv('GITHUB_REPOSITORY')

    g = Github(github_token)
    repo = g.get_repo(repository)
    issue_number = int(os.getenv('GITHUB_EVENT_ISSUE_NUMBER'))

    issue = repo.get_issue(issue_number)
    issue.add_to_labels(team_name)

    print(f'Label "{team_name}" added to issue #{issue_number}')
else:
    print('Team name not found in the issue description.')
EOF
