name: Label Issue

on:
  issues:
    types:
      - opened

jobs:
  label-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Issue Label
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = github.event.issue;

            if (issue && issue.body) {
              const issueDescription = issue.body;
              const teamNameMatch = issueDescription.match(/### Team\s*\n\s*([^\n]+)/);
              
              if (teamNameMatch && teamNameMatch[1]) {
                const teamName = teamNameMatch[1].trim();
                const labels = [teamName];
                
                github.issues.addLabels({
                  issue_number: issue.number,
                  owner: github.context.repo.owner,
                  repo: github.context.repo.repo,
                  labels: labels,
                });

                console.log(`Label "${teamName}" added to issue #${issue.number}`);
              } else {
                console.log('Team name not found in the issue description.');
              }
            } else {
              console.log('Issue body not available.');
            }
